/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Guest
 */
public class MainMenuForm extends javax.swing.JFrame {

    /**
     * Creates new form MainMenuForm
     */
    public MainMenuForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        mainMenuBar = new javax.swing.JMenuBar();
        mainMenu = new javax.swing.JMenu();
        ItmCreateGraduate = new javax.swing.JMenuItem();
        itmLowGraduated = new javax.swing.JMenuItem();
        itmModifications = new javax.swing.JMenuItem();
        itmQuery = new javax.swing.JMenuItem();
        itmStatistics = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblTitle.setText("Sistema Institucional de Egresados");

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo-uabc.png"))); // NOI18N
        lblLogo.setText("jLabel2");

        mainMenu.setText("Menú");

        ItmCreateGraduate.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        ItmCreateGraduate.setText("Alta Egresado");
        ItmCreateGraduate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItmCreateGraduateActionPerformed(evt);
            }
        });
        mainMenu.add(ItmCreateGraduate);

        itmLowGraduated.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        itmLowGraduated.setText("Baja Egresado");
        itmLowGraduated.setAlignmentX(0.1F);
        itmLowGraduated.setAlignmentY(0.1F);
        itmLowGraduated.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmLowGraduatedActionPerformed(evt);
            }
        });
        mainMenu.add(itmLowGraduated);

        itmModifications.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        itmModifications.setText("Modificaciones");
        itmModifications.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmModificationsActionPerformed(evt);
            }
        });
        mainMenu.add(itmModifications);

        itmQuery.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        itmQuery.setText("Consulta");
        itmQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmQueryActionPerformed(evt);
            }
        });
        mainMenu.add(itmQuery);

        itmStatistics.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        itmStatistics.setText("Estadísticas");
        itmStatistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmStatisticsActionPerformed(evt);
            }
        });
        mainMenu.add(itmStatistics);

        mainMenuBar.add(mainMenu);

        setJMenuBar(mainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLogo)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItmCreateGraduateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItmCreateGraduateActionPerformed
        this.setVisible(false);
        new CreateGraduateForm().setVisible(true);
    }//GEN-LAST:event_ItmCreateGraduateActionPerformed

    private void itmModificationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmModificationsActionPerformed
        this.setVisible(false);
        new UpdateGraduateForm().setVisible(true);
    }//GEN-LAST:event_itmModificationsActionPerformed

    private void itmQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmQueryActionPerformed
        this.setVisible(false);
        new ListGraduateForm().setVisible(true);
    }//GEN-LAST:event_itmQueryActionPerformed

    private void itmStatisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmStatisticsActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new StatisticsGraduatesForm().setVisible(true);
    }//GEN-LAST:event_itmStatisticsActionPerformed

    private void itmLowGraduatedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmLowGraduatedActionPerformed
        this.setVisible(false);
        new DeleteGraduateForm().setVisible(true);
    }//GEN-LAST:event_itmLowGraduatedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItmCreateGraduate;
    private javax.swing.JMenuItem itmLowGraduated;
    private javax.swing.JMenuItem itmModifications;
    private javax.swing.JMenuItem itmQuery;
    private javax.swing.JMenuItem itmStatistics;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JMenu mainMenu;
    private javax.swing.JMenuBar mainMenuBar;
    // End of variables declaration//GEN-END:variables

}
