/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author vmascareno
 */
public class StatisticsGraduatesForm extends javax.swing.JFrame {

    /**
     * Creates new form Statistics
     */
    public StatisticsGraduatesForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGraduades = new javax.swing.JLabel();
        lblComputation = new javax.swing.JLabel();
        lblMechatronic = new javax.swing.JLabel();
        lblMechanic = new javax.swing.JLabel();
        lblElectric = new javax.swing.JLabel();
        lblElectronic = new javax.swing.JLabel();
        lblCivil = new javax.swing.JLabel();
        lblIndustrial = new javax.swing.JLabel();
        lblEnergies = new javax.swing.JLabel();
        bioengineering = new javax.swing.JLabel();
        lblPercentageComputation = new javax.swing.JLabel();
        lblPercentageMechanic = new javax.swing.JLabel();
        lblPercentageMechatronics = new javax.swing.JLabel();
        lblPercentageElectric = new javax.swing.JLabel();
        lblPercentageElectronics = new javax.swing.JLabel();
        lblPercentageCivil = new javax.swing.JLabel();
        lblPercentageIndustrial = new javax.swing.JLabel();
        lblPercentageEnergies = new javax.swing.JLabel();
        lblPercentageBioengineering = new javax.swing.JLabel();
        government = new javax.swing.JLabel();
        lblPercentagePrivates = new javax.swing.JLabel();
        lblPrivates = new javax.swing.JLabel();
        lblPercentageGovernment = new javax.swing.JLabel();
        lblTypeOfJob = new javax.swing.JLabel();
        lblSex = new javax.swing.JLabel();
        lblFemale = new javax.swing.JLabel();
        lblMale = new javax.swing.JLabel();
        lblPercentageSexFemale = new javax.swing.JLabel();
        lblPercentageSexMale = new javax.swing.JLabel();
        returnMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblGraduades.setText("Egresados por carrera:");

        lblComputation.setText("Ingeniero en Computación");

        lblMechatronic.setText("Ingeniero en Mecatrónica");

        lblMechanic.setText("Ingeniero Mecanico");

        lblElectric.setText("Ingeniero en Electrica");

        lblElectronic.setText("Ingeniero en Electronica");

        lblCivil.setText("Ingeniero Civil");

        lblIndustrial.setText("Ingeniero Industrial");

        lblEnergies.setText("Ingeniero en Energias Renovables");

        bioengineering.setText("Bioingeniero");

        lblPercentageComputation.setText("0 %");

        lblPercentageMechanic.setText("0 %");

        lblPercentageMechatronics.setText("0 %");

        lblPercentageElectric.setText("0 %");

        lblPercentageElectronics.setText("0 %");

        lblPercentageCivil.setText("0 %");

        lblPercentageIndustrial.setText("0 %");

        lblPercentageEnergies.setText("0 %");

        lblPercentageBioengineering.setText("0 %");

        government.setText("Empresas de Gobierno");

        lblPercentagePrivates.setText("0 %");

        lblPrivates.setText("Empresas Privadas");

        lblPercentageGovernment.setText("0 %");

        lblTypeOfJob.setText("Tipo de Trabajo:");

        lblSex.setText("Sexo:");

        lblFemale.setText("Femenino");

        lblMale.setText("Masculino");

        lblPercentageSexFemale.setText("0 %");

        lblPercentageSexMale.setText("0 %");

        returnMenu.setText("Regresar");
        returnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMechatronic)
                                    .addComponent(lblComputation, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMechanic)
                                    .addComponent(lblElectric)
                                    .addComponent(lblElectronic)
                                    .addComponent(lblCivil)
                                    .addComponent(lblIndustrial)
                                    .addComponent(lblGraduades))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPercentageIndustrial)
                                    .addComponent(lblPercentageCivil)
                                    .addComponent(lblPercentageElectronics)
                                    .addComponent(lblPercentageElectric)
                                    .addComponent(lblPercentageMechanic)
                                    .addComponent(lblPercentageComputation)
                                    .addComponent(lblPercentageMechatronics)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bioengineering)
                                    .addComponent(government)
                                    .addComponent(lblEnergies)
                                    .addComponent(lblTypeOfJob))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPercentageBioengineering)
                                    .addComponent(lblPercentageEnergies)
                                    .addComponent(lblPercentagePrivates)
                                    .addComponent(lblPercentageGovernment)
                                    .addComponent(lblPercentageSexFemale)
                                    .addComponent(lblPercentageSexMale))))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPrivates)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMale)
                            .addComponent(lblFemale)
                            .addComponent(lblSex))
                        .addGap(0, 206, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(returnMenu)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGraduades)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComputation)
                    .addComponent(lblPercentageComputation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMechatronic)
                    .addComponent(lblPercentageMechatronics))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMechanic)
                    .addComponent(lblPercentageMechanic))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblElectric)
                    .addComponent(lblPercentageElectric))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblElectronic)
                    .addComponent(lblPercentageElectronics))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCivil)
                    .addComponent(lblPercentageCivil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIndustrial)
                    .addComponent(lblPercentageIndustrial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnergies)
                    .addComponent(lblPercentageEnergies))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bioengineering)
                    .addComponent(lblPercentageBioengineering))
                .addGap(18, 18, 18)
                .addComponent(lblTypeOfJob)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPercentageGovernment)
                    .addComponent(government))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrivates)
                    .addComponent(lblPercentagePrivates))
                .addGap(18, 18, 18)
                .addComponent(lblSex)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFemale)
                    .addComponent(lblPercentageSexFemale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMale)
                    .addComponent(lblPercentageSexMale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(returnMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnMenuActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new MainMenuForm().setVisible(true);
    }//GEN-LAST:event_returnMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatisticsGraduatesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatisticsGraduatesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatisticsGraduatesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatisticsGraduatesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StatisticsGraduatesForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bioengineering;
    private javax.swing.JLabel government;
    private javax.swing.JLabel lblCivil;
    private javax.swing.JLabel lblComputation;
    private javax.swing.JLabel lblElectric;
    private javax.swing.JLabel lblElectronic;
    private javax.swing.JLabel lblEnergies;
    private javax.swing.JLabel lblFemale;
    private javax.swing.JLabel lblGraduades;
    private javax.swing.JLabel lblIndustrial;
    private javax.swing.JLabel lblMale;
    private javax.swing.JLabel lblMechanic;
    private javax.swing.JLabel lblMechatronic;
    private javax.swing.JLabel lblPercentageBioengineering;
    private javax.swing.JLabel lblPercentageCivil;
    private javax.swing.JLabel lblPercentageComputation;
    private javax.swing.JLabel lblPercentageElectric;
    private javax.swing.JLabel lblPercentageElectronics;
    private javax.swing.JLabel lblPercentageEnergies;
    private javax.swing.JLabel lblPercentageGovernment;
    private javax.swing.JLabel lblPercentageIndustrial;
    private javax.swing.JLabel lblPercentageMechanic;
    private javax.swing.JLabel lblPercentageMechatronics;
    private javax.swing.JLabel lblPercentagePrivates;
    private javax.swing.JLabel lblPercentageSexFemale;
    private javax.swing.JLabel lblPercentageSexMale;
    private javax.swing.JLabel lblPrivates;
    private javax.swing.JLabel lblSex;
    private javax.swing.JLabel lblTypeOfJob;
    private javax.swing.JButton returnMenu;
    // End of variables declaration//GEN-END:variables
}
